### ISSUE TITLE
FastDL Settings can't be modified

### ISSUE THREAD

**Issue by ImBenny95** [sheybey/fastdl#2]
I can't delete / reset FastDL Module.

Can't turn off autoindex, and delete options.

I click save after modify but it keeps the previous settings.

**Comment by sheybey** [comment]
> I can't delete / reset FastDL Module.

To delete a fastdl instance, use `rm -rf`.

> Can't turn off autoindex, and delete options.

I don't know what you mean by "autoindex."

To disallow users from deleting maps, do not give them login permissions. Admin merely determines whether a logged-in user can add/remove other users. If you require a finer permissions model, I encourage you to make the changes yourself! I would be happy to review a pull request.

> I click save after modify but it keeps the previous settings.

There is no "save" button in this application. What are you talking about?

**Comment by ImBenny95** [comment]
> > I can't delete / reset FastDL Module.
> 
> To delete a fastdl instance, use `rm -rf`.
> 
> > Can't turn off autoindex, and delete options.
> 
> I don't know what you mean by "autoindex."
> 
> To disallow users from deleting maps, do not give them login permissions. Admin merely determines whether a logged-in user can add/remove other users. If you require a finer permissions model, I encourage you to make the changes yourself! I would be happy to review a pull request.
> 
> > I click save after modify but it keeps the previous settings.
> 
> There is no "save" button in this application. What are you talking about?

I am very sorry for late reply but I use Github very rare and I wrote my experiences about this on GameAP Forum and I forget that I've asked there too.

Unfortunately I don't use GameAP anymore. I switched to OGP because I had lot of problems with GameAP. :(
I always recieved error messages. I couldn't make it work with Nginx. After about some days of trying I gave up but thank you for help! :/

OGP uses its own service on different port it doesn't even need Nginx or Apache. It is more reliable to me because maybe my server has some compatibility problems with GameAP. I am sad about this because the GameAP design is much better looking.

**Comment by sheybey** [comment]
This software has nothing to do with GameAP. It is a toy application that I wrote in 2 hours several years ago on a whim. I'm really not sure how you ended up here.
